# Inspired by Zed's One Dark implementation
# One Dark is released under the MIT License and Copyright (c) 2014 GitHub Inc.

base00 = "#282c33"
base01 = "#363c46"
base02 = "#464b57"
base03 = "#5d636f"
base04 = "#878a98"
base05 = "#acb2be"
base06 = "#d0d4da"
base07 = "#fafafa"
base08 = "#d07277"
base09 = "#bf956a"
base0A = "#dfc184"
base0B = "#a1c181"
base0C = "#6eb4bf"
base0D = "#73ade9"
base0E = "#b477cf"
base0F = "#b1574b"

term_bg = "#252A32"

vcs_added = "#27a657"
vcs_modified = "#d3b020"
vcs_deleted = "#e06c76"
