# Inspired by Zed's One Dark implementation
# One Dark is released under the MIT License and Copyright (c) 2014 GitHub Inc.

base00 = "#252930"
base01 = "#333943"
base02 = "#434854"
base03 = "#5a606c"
base04 = "#848795"
base05 = "#a9afbb"
base06 = "#cdd1d7"
base07 = "#f7f7f7"
base08 = "#d2797e"
base09 = "#ceb395"
base0A = "#e1c68d"
base0B = "#bad2a2"
base0C = "#76b8c2"
base0D = "#84b5ea"
base0E = "#c08ed7"
base0F = "#c37c73"

term_bg = "#252930"

vcs_added = "#27a657"
vcs_modified = "#d3b020"
vcs_deleted = "#e06c76"
