# Based on Zed's One Dark implementation
# https://github.com/zed-industries/zed/tree/main/assets/themes/one

# bg0: Alternate background (status line, float)
# bg1: Default background
# bg2: Alternate background (colorcolumn, folds)
# bg3: Alternate background (cursorline)
# bg4: Conceal, border foreground
# fg0: Alternate foreground
# fg1: Default foreground
# fg2: Alternate foreground (status line)
# fg3: Alternate foreground (line numbers, fold columns)
# sel0: Popup background, visual selection background
# sel1: Popup selection background, search background

black   = "#252530"
red     = "#d8647e"
green   = "#7fa563"
yellow  = "#f3be7c"
blue    = "#6e94b2"
magenta = "#bb9dbd"
cyan    = "#aeaed1"
white   = "#cdcdcd"
orange  = "#f5cb96"
pink    = "#c9b1ca"

bg0     = "#0c0c0d"
bg1     = "#141415"
bg2     = "#252530"
bg3     = "#434344"
bg4     = "#5b5b5b"

fg0     = "#dcdcdc"
fg1     = "#cdcdcd"
fg2     = "#b9b9b9"
fg3     = "#a4a4a4"

comment = "#909090"

sel0    = "#252530"
sel1    = "#434344"
