# Based on Vague (https://github.com/vague2k/vague.nvim)

rosewater = "#e8b589"  # Macros, Cursor
flamingo = "#f3be7c"  # Unknown
pink = "#aeaed1"  # Escape Sequences, Regex
mauve = "#6e94b2"  # Keywords
red = "#b4d4cf"  # Builtins, Errors
maroon = "#bb9dbd"  # Parameters
peach = "#e0a363"  # Constants, Numbers, Warnings
yellow = "#9bb4bc"  # Classes, Types, Enums, Attributes
green = "#e8b589"  # Strings
teal = "#6e94b2"  # Enum Variants, Information, Search BG
sky = "#90a0b5"  # Operators
sapphire = "#7e98e8"  # Unused
blue = "#c48282"  # Methods, Functions, Property
lavender = "#c3c3d5"  # Active Line Number
text = "#cdcdcd"  # Foreground, Cursor Line @ 10%
subtext1 = "#c3c3d5"
subtext0 = "#aeaed1"
overlay2 = "#90a0b5"  # Comments
overlay1 = "#878787"  # Line Numbers
overlay0 = "#606079"
surface2 = "#405065"
surface1 = "#333738"
surface0 = "#252530"
base = "#141415"  # Background
mantle = "#252530"
crust = "#252530"
