# Based on Nightfox (https://github.com/EdenEast/nightfox.nvim)

# bg0: Status line, float
# bg1: Default
# bg2: Colorcolumn, fold
# bg3: Cursor line
# bg4: Conceal, border
# fg0: Alternate
# fg1: Default
# fg2: Status line
# fg3: Line numbers, fold column
# sel0: Popup, visual selection
# sel1: Popup selection, search

black = "#393b44"
red = "#c94f6d"
green = "#81b29a"
yellow = "#dbc074"
blue = "#719cd6"
magenta = "#9d79d6"
cyan = "#63cdcf"
white = "#dfdfe0"
orange = "#f4a261"
pink = "#d67ad2"
comment = "#738091"
bg0 = "#131a24"
bg1 = "#192330"
bg2 = "#212e3f"
bg3 = "#29394f"
bg4 = "#39506d"
fg0 = "#d6d6d7"
fg1 = "#cdcecf"
fg2 = "#aeafb0"
fg3 = "#71839b"
sel0 = "#2b3b51"
sel1 = "#3c5372"
