# Based on Dayfox (https://github.com/EdenEast/nightfox.nvim)

# bg0: Alternate background (status line, float)
# bg1: Default background
# bg2: Alternate background (colorcolumn, folds)
# bg3: Alternate background (cursorline)
# bg4: Conceal, border foreground
# fg0: Alternate foreground
# fg1: Default foreground
# fg2: Alternate foreground (status line)
# fg3: Alternate foreground (line numbers, fold columns)
# sel0: Popup background, visual selection background
# sel1: Popup selection background, search background

black   = "#352c24"
red     = "#a5222f"
green   = "#396847"
yellow  = "#AC5402"
blue    = "#2848a9"
magenta = "#6e33ce"
cyan    = "#287980"
white   = "#f2e9e1"
orange  = "#955f61"
pink    = "#a440b5"

bg0     = "#e4dcd4"
bg1     = "#f6f2ee"
bg2     = "#dbd1dd"
bg3     = "#d3c7bb"
bg4     = "#aab0ad"

fg0     = "#302b5d"
fg1     = "#3d2b5a"
fg2     = "#643f61"
fg3     = "#824d5b"

comment = "#837a72"

sel0    = "#e7d2be"
sel1    = "#a4c1c2"

