# Based on Dayfox (https://github.com/EdenEast/nightfox.nvim)

# bg0: Status line, float
# bg1: Default
# bg2: Colorcolumn, fold
# bg3: Cursor line
# bg4: Conceal, border
# fg0: Alternate
# fg1: Default
# fg2: Status line
# fg3: Line numbers, fold column
# sel0: Popup, visual selection
# sel1: Popup selection, search

black = "#352c24"
red = "#a5222f"
green = "#396847"
yellow = "#AC5402"
blue = "#2848a9"
magenta = "#6e33ce"
cyan = "#287980"
white = "#f2e9e1"
orange = "#955f61"
pink = "#a440b5"
comment = "#837a72"
bg0 = "#e4dcd4"
bg1 = "#f6f2ee"
bg2 = "#dbd1dd"
bg3 = "#d3c7bb"
bg4 = "#aab0ad"
fg0 = "#302b5d"
fg1 = "#3d2b5a"
fg2 = "#643f61"
fg3 = "#824d5b"
sel0 = "#e7d2be"
sel1 = "#a4c1c2"
