# Inspired by Zed's One Light implementation
# https://github.com/zed-industries/zed/tree/main/assets/themes/one

# base00 - Default Background
# base01 - Lighter Background (Used for status bars, line number and folding marks)
# base02 - Selection Background
# base03 - Comments, Invisibles, Line Highlighting
# base04 - Dark Foreground (Used for status bars)
# base05 - Default Foreground, Caret, Delimiters, Operators
# base06 - Light Foreground (Not often used)
# base07 - Light Background (Not often used)
# base08 - Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
# base09 - Integers, Boolean, Constants, XML Attributes, Markup Link Url
# base0A - Classes, Markup Bold, Search Text Background
# base0B - Strings, Inherited Class, Markup Code, Diff Inserted
# base0C - Support, Regular Expressions, Escape Characters, Markup Quotes
# base0D - Functions, Methods, Attribute IDs, Headings
# base0E - Keywords, Storage, Selector, Markup Italic, Diff Changed
# base0F - Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>

base00 = "#f3f2f2"
base01 = "#e6e0e0"
base02 = "#d8cfcf"
base03 = "#958d8d"
base04 = "#6b5d5d"
base05 = "#4c4949"
base06 = "#363636"
base07 = "#d8cfcf"
base08 = "#ae4737"
base09 = "#9d611d"
base0A = "#bd8700"
base0B = "#5c9052"
base0C = "#2e75a8"
base0D = "#30629e"
base0E = "#7b3c80"
base0F = "#b15c50"

vcs_added = "#27a657"
vcs_modified = "#d3b020"
vcs_deleted = "#e06c76"
