# Based on Tomorrow (https://github.com/chriskempson/tomorrow-theme)

rosewater = "#503124"
flamingo = "#4f2c36"
pink = "#5e3060"
mauve = "#5b223a"
red = "#70191d"
maroon = "#722d18"
peach = "#8b411a"
yellow = "#644406"
green = "#4d5225"
teal = "#3c592d"
sky = "#275953"
sapphire = "#365c5c"
blue = "#315f95"
lavender = "#5e4b7b"
text = "#383841"
subtext1 = "#3e3d4b"
subtext0 = "#505056"
overlay2 = "#78777f"
overlay1 = "#88878e"
overlay0 = "#98989d"
surface2 = "#a8a8aa"
surface1 = "#cacaca"
surface0 = "#dadad8"
base = "#f3f1e9"
mantle = "#eae9e3"
crust = "#e0e0dc"
