# Based on Tomorrow Night by Chris Kempson
# https://github.com/chriskempson/tomorrow-theme

base00 = "#1d1f21"
base01 = "#282a2e"
base02 = "#373b41"
base03 = "#4d5057"
base04 = "#969896"
base05 = "#c5c8c6"
base06 = "#e8e8e8"
base07 = "#f8f8f8"
base08 = "#cc6666"
base09 = "#de935f"
base0A = "#f0c674"
base0B = "#b5bd68"
base0C = "#8abeb7"
base0D = "#81a2be"
base0E = "#b294bb"
base0F = "#a16946"
