# Based on Gruvbox (https://github.com/morhetz/gruvbox)

rosewater = "#b16286"
flamingo = "#98971a"
pink = "#b16286"
mauve = "#d3869b"
red = "#fb4934"
maroon = "#d65d0e"
peach = "#fe8019"
yellow = "#fabd2f"
green = "#b8bb26"
teal = "#689d6a"
sky = "#8ec07c"
sapphire = "#458588"
blue = "#83a598"
lavender = "#8ec07c"
text = "#ebdbb2"
subtext1 = "#ebdbb2"
subtext0 = "#fbf1c7"
overlay2 = "#a89984"
overlay1 = "#bdae93"
overlay0 = "#a89984"
surface2 = "#665c54"
surface1 = "#504945"
surface0 = "#3c3836"
base = "#282828"
mantle = "#3c3836"
crust = "#1d2021"
