# Based on Tomorrow Night (https://github.com/chriskempson/tomorrow-theme)

rosewater = "#ab7e8a"
flamingo = "#c49f91"
pink = "#c094c2"
mauve = "#bd6d8f"
red = "#d46269"
maroon = "#d57d62"
peach = "#de9974"
yellow = "#f0c674"
green = "#b5bd82"
teal = "#9fbd8f"
sky = "#87c1b9"
sapphire = "#7ea8a7"
blue = "#81acd9"
lavender = "#b3a7db"
text = "#d2d9ed"
subtext1 = "#bac0d2"
subtext0 = "#a6acbc"
overlay2 = "#9499a4"
overlay1 = "#82858d"
overlay0 = "#6f7078"
surface2 = "#595b63"
surface1 = "#45474e"
surface0 = "#313138"
base = "#1e1e22"
mantle = "#17171b"
crust = "#101010"
