# Based on Everforest by Sainnhe Park
# https://github.com/sainnhe/everforest

base00 = "#fffbef"
base01 = "#f2efdf"
base02 = "#e8e5d5"
base03 = "#939f91"
base04 = "#a6b0a0"
base05 = "#5c6a72"
base06 = "#708089"
base07 = "#829181"
base08 = "#3a94c5"
base09 = "#df69ba"
base0A = "#dfa000"
base0B = "#35a77c"
base0C = "#f57d26"
base0D = "#8da101"
base0E = "#f85552"
base0F = "#bec5b2"
